# Configuration

Use **pytorch** conda enviroment

# 1) PyTorch Tensors and Gradients

A gradient is simply the rate of change of one value with respect to another. While gradients have their roots in calculus, we won't be getting into any of their mathematical details, but rather we'll focus on the practical implications of them.

In neural networks, gradients tell us how much our model's loss changes when we make a small adjustment to each parameter (weight or bias). If a weight has a gradient of `-0.5`, increasing that weight slightly would decrease the model's loss. The loss is how we measure how wrong our model is - it's a single number calculated by a loss function that quantifies the difference between what your model predicted and the actual values. In other words, neural networks can be viewed as an optimization problem where we use these gradients to adjust our parameters and minimize this loss as much as possible

# 2) Creating Tensors and Data Types

**Tensors** are like NumPy arrays but with extra features for building neural networks. They can automatically track mathematical operations (when enabled) to compute gradients for training, and they can run efficiently on GPUs for faster computation. Just like NumPy arrays, tensors store multi-dimensional data and support mathematical operations, but PyTorch adds the gradient tracking capability that makes neural network training possible. In PyTorch, tensors are implemented by the `torch.Tensor class`.

We can create tensors from Python lists or NumPy arrays, or generate them using helper functions. Key creation APIs include the `torch.tensor` [function](https://docs.pytorch.org/docs/stable/generated/torch.tensor.html), `torch.arange` [function](https://docs.pytorch.org/docs/stable/generated/torch.arange.html), `torch.zeros` [function](https://docs.pytorch.org/docs/stable/generated/torch.zeros.html), and `torch.ones` [function](https://docs.pytorch.org/docs/stable/generated/torch.ones.html).

Once you have a tensor, you can inspect its properties using the `.dtype` attribute to see its data type and the `.shape` attribute to see its dimensions.

 These attributes are perfect for understanding your tensor's structure and ensuring compatibility with mathematical operations.


In [1]:
import torch

# Create a tensor from a Python list - dtype is inferred from the data
heights = torch.tensor([1.72, 1.85, 1.60])
print(heights.dtype, heights.shape)  # torch.float32 torch.Size([3])
ages = torch.tensor([18, 22, 27])
print(ages.dtype)  # torch.int64

# Override the inferred dtype by specifying it explicitly
ages_float = torch.tensor([18, 22, 27], dtype=torch.float32)
print(ages_float.dtype)  # torch.float32

# Create a tensor using range-like generation (similar to NumPy's arange)
days = torch.arange(1, 5)
print(days, days.dtype)  # tensor([1, 2, 3, 4]) torch.int64

# Create zero-initialized tensors with specified shape
zeros_2x3 = torch.zeros((2, 3))
print(zeros_2x3.dtype, zeros_2x3.shape)  # torch.float32 torch.Size([2, 3])

# Create ones-initialized tensors with specified shape
ones_3 = torch.ones(3)
print(ones_3.dtype, ones_3.shape)  # torch.float32 torch.Size([3])

torch.float32 torch.Size([3])
torch.int64
torch.float32
tensor([1, 2, 3, 4]) torch.int64
torch.float32 torch.Size([2, 3])
torch.float32 torch.Size([3])


**Impact of Data Types**

The dtype (data type) you choose affects both memory usage and computation speed. Here's what you need to know about them:

* `float32` is the standard for neural network inputs and parameters. It offers good precision while using half the memory of float64.

* `int64` works well for labels, indices, and counting. Use this when you need whole numbers.

* `float64` provides higher precision but uses more memory. Most ML tasks don't need this level of precision

## Instructions

1. Create a 1D tensor called `daily_steps` with the following data: [3500, 7200, 6100, 8200, 4000] (let PyTorch infer the dtype).

1. Create a 1D tensor of floats called `temperatures_c` with the following data: [18.5, 20.1, 22.0, 19.8] with float64 dtype.

1. Create a tensor called `week_days` containing integers from 1 to 7 (inclusive) using a range-like function.

1. Create a 2x4 tensor of zeros called `zeros_matrix`.

1. Print each tensor's `dtype` and `shape`.


In [2]:
import torch

# Create the tensors defined in the instructions
daily_steps = torch.tensor([3500, 7200, 6100, 8200, 4000])
print(daily_steps.dtype, daily_steps.shape)

temperatures_c = torch.tensor([18.5, 20.1, 22.0, 19.8],dtype=torch.float64)
print(temperatures_c.dtype, temperatures_c.shape)

week_days = torch.arange(1,8)
print(week_days.dtype, week_days.shape)

zeros_matrix = torch.zeros((2,4))
print(zeros_matrix.dtype, zeros_matrix.shape)

torch.int64 torch.Size([5])
torch.float64 torch.Size([4])
torch.int64 torch.Size([7])
torch.float32 torch.Size([2, 4])


# 3) Shapes, Indexing, and Reshaping

 let's focus on one of the most important skills you'll need when working in PyTorch: manipulating tensor shapes. Neural network models are super picky about **shapes**. Models expect tensors to be a specific shape, and if the data doesn't match, we'll get an error.

 **Adding and Removing Dimensions**

 Sometimes we'll need to add or remove dimensions from our tensors to mold them into the shape we need. PyTorch provides the `Tensor.squeeze` method and `Tensor.unsqueeze` method for these purposes.

 ```Python
 days = torch.arange(1, 8)

# unsqueeze() adds a dimension of size 1 at the specified position
days_column = days.unsqueeze(1)           # Add dimension at position 1
days_row = days.unsqueeze(0)              # Add dimension at position 0
print(days_column.shape, days_row.shape)  # torch.Size([7, 1]) torch.Size([1, 7])

# squeeze() removes dimensions of size 1
back_to_original = steps_column.squeeze(1)  # Remove the size-1 dimension
print(back_to_original.shape)  # torch.Size([7])

# Basic indexing to get subsets of data
first_three_days = daily_steps[:3]
print(first_three_days)  # tensor([1, 2, 3])
```

**Key points:**

* `unsqueeze(dim)` requires you to specify where to add the new dimension

* `squeeze(dim)` can target a specific dimension, or remove all size-1 dims if no is argument given

* Both operations return NEW tensors; the original tensor remains unchanged

**Reshaping Tensors**

`view()` vs `reshape()`:

* `view()` is faster but requires the tensor to be stored in contiguous memory. It returns a new tensor that shares the same underlying data as the original.

* `reshape()` is more flexible and will copy data if needed when the tensor isn't contiguous.

* Start with `view()` since it's more efficient. If you get an error about contiguity, switch to `reshape()`.

In [4]:
# Create random data simulating sensor readings (12 total readings)
sensor_data = torch.randn(12)  
print(sensor_data.shape)  # torch.Size([12])

# Reshape into a 3x4 grid (e.g., 3 sensors, 4 time periods each)
sensor_grid = sensor_data.view(3, 4)
print(sensor_grid.shape)  # torch.Size([3, 4])
print(sensor_grid)
# tensor([[-0.1234,  0.5678, -0.9012,  0.3456],
#         [ 0.7890, -0.2345,  0.6789, -0.4567],
#         [ 0.8901, -0.5432,  0.2109, -0.6543]])

# Alternative: use reshape() which works the same way for most cases
sensor_grid_alt = torch.reshape(sensor_data, (3, 4))
print(sensor_grid_alt.shape)  # torch.Size([3, 4])

# Important: view() returns a NEW tensor but shares the same data
print(sensor_data.shape)  # torch.Size([12]) - original shape unchanged

torch.Size([12])
torch.Size([3, 4])
tensor([[-0.2262, -0.8426,  1.7904, -1.2051],
        [-1.0934,  0.6138,  0.0991,  0.4442],
        [-0.5805,  1.0303, -0.5923, -0.9482]])
torch.Size([3, 4])
torch.Size([12])


**Accessing Tensor Data**

We can extract values from tensors using indexing and slicing, just like with NumPy arrays and Python lists.

```Python
scores = torch.tensor([85, 92, 78, 96, 88, 91, 83])
first_score = scores[0]     # tensor(85)
first_three = scores[:3]    # tensor([85, 92, 78])
last_two = scores[-2:]      # tensor([91, 83])
```


In [6]:
import torch

temperatures = torch.tensor([18.0, 19.5, 21.2, 20.3, 19.1, 18.7])

# Reshape temperatures according to the instructions
temperatures_col = temperatures.unsqueeze(1)

#Reshape into 2x3 tensor
grid_temps = torch.reshape(temperatures,(2,3))

#take first 3 entries
morning_readings = temperatures[0:3]
print(morning_readings)
                           

tensor([18.0000, 19.5000, 21.2000])


# 4) Concatenation and Stacking

Real neural network workflows involve combining data from multiple sources. We might need to **merge** training data from different files, combine predictions from multiple models, or **stack** individual samples into batches. PyTorch gives us two main tools for this: concatenation and stacking.

Use the `torch.cat` function to concatenate tensors along an existing dimension. This combines tensors by placing them **end-to-end** along a specified axis, similar to joining two lists together. The tensors must have the **same shape** in all dimensions except the one you're concatenating along.

Use the `torch.stack` function to stack tensors along a new dimension. This creates a new dimension by placing tensors alongside each other, like organizing separate data arrays into layers. All input tensors must have exactly the same shape since you're adding a completely new dimension.

**When to use each:**

1. **Concatenation** increases the size along an existing dimension. Use this to:

    * Combine datasets from multiple sources

    * Add more training examples to your data

    * Merge results from different time periods

1. **Stacking** creates a new dimension entirely. Use this to:

    * Create batches for model training

    * Compare data across different categories

    * Organize related datasets for parallel processing

In [9]:
# Daily sales data from two different stores
store_a = torch.tensor([[120, 85],   # Day 1: online, in-store sales
                        [95, 120]])  # Day 2: online, in-store sales
store_b = torch.tensor([[110, 90],   # Day 1: online, in-store sales  
                        [180, 135]]) # Day 2: online, in-store sales

# Concatenate: combine all sales data into one dataset
all_sales = torch.cat([store_a, store_b], dim=0)
print(all_sales)   
print(all_sales.shape)  # torch.Size([4, 2]) - 4 days total

# Stack: organize by store for comparison
by_store = torch.stack([store_a, store_b], dim=0)
print(by_store)  
print(by_store.shape)   # torch.Size([2, 2, 2]) - 2 stores, 2 days each

tensor([[120,  85],
        [ 95, 120],
        [110,  90],
        [180, 135]])
torch.Size([4, 2])
tensor([[[120,  85],
         [ 95, 120]],

        [[110,  90],
         [180, 135]]])
torch.Size([2, 2, 2])


## Instructions

1. Join `week1_interactions` and `week2_interactions` row-wise into combined_interactions.

1. Join `week1_interactions` and `week2_interactions` along a new first dimension into weekly_comparison.

1. Print the shapes of both results to see the difference.


In [10]:
import torch

week1_interactions = torch.tensor([[120, 85],   
                                   [95, 120],
                                   [200, 150]])
week2_interactions = torch.tensor([[110, 90],
                                   [180, 135],
                                   [75, 80]])
                                   
# Combine the data in two different ways
combined_interactions = torch.cat([week1_interactions, week2_interactions], dim=0)

weekly_comparison = torch.stack([week1_interactions, week2_interactions], dim=0)

print(combined_interactions.shape, weekly_comparison.shape)

torch.Size([6, 2]) torch.Size([2, 3, 2])


# 5) Broadcasting

[Broadcasting](https://docs.pytorch.org/docs/stable/notes/broadcasting.html) is a set of rules that determines how PyTorch handles operations between tensors of different shapes.

When we perform mathematical operations like addition, subtraction, or multiplication between two tensors, PyTorch checks if their shapes are compatible. If the shapes don't match exactly, broadcasting rules determine whether the operation can still proceed by automatically expanding the smaller tensor to match the larger one's shape.

Broadcasting saves memory and makes code faster because PyTorch doesn't actually create expanded copies of the data, it just performs the operation as if the smaller tensor had been expanded.

**Important**: Broadcasting doesn't work for all shape combinations. When shapes are incompatible, we'll need to manually reshape our tensors. Here are the rules for broadcasting:

1. **Start from the rightmost** dimension in both tensors

1. **Dimensions are compatible** if they're equal, if one of them is 1, or if one doesn't exist (missing dimensions are assumed to be size 1)

1. **The resulting tensor** shape takes the larger size in each dimension, working right to left

**Example 1: Scalar Broadcasting**

Scalar broadcasting is the simplest case: a single value gets added to every element in the tensor. This works with tensors of any shape because scalars are compatible with all dimensions.

In [11]:
data = torch.tensor([[1.0, 2.0, 3.0],
                     [4.0, 5.0, 6.0]])  # shape: (2, 3)
scalar = 10.0                           # Python scalar (no need to convert to tensor)
result = data + scalar                  # result shape: (2, 3)
print(result)
# tensor([[11., 12., 13.],
#         [14., 15., 16.]])

tensor([[11., 12., 13.],
        [14., 15., 16.]])


**Example 2: Broadcasting with Missing Dimensions**

Here's where broadcasting gets interesting. The **row_vector has shape (3,)** while data has `shape (2, 3)`. Broadcasting treats the missing dimension as size 1, so it becomes (1, 3) conceptually, then broadcasts across the 2 rows.

In [12]:
data = torch.tensor([[1.0, 2.0, 3.0],
                     [4.0, 5.0, 6.0]])              # shape: (2, 3)
row_vector = torch.tensor([100.0, 200.0, 300.0])    # shape: (3,)
result = data + row_vector
print(result)
# tensor([[101., 202., 303.],
#         [104., 205., 306.]])

tensor([[101., 202., 303.],
        [104., 205., 306.]])


**Example 3: Broadcasting with Size-1 Dimensions**

The `col_vector` has a size-1 dimension in the second position `(2, 1)`. This single column broadcasts across all 3 columns of data, with the first value (1000.0) added to the entire first row, and the second value (2000.0) added to the entire second row.

In [13]:
data = torch.tensor([[1.0, 2.0, 3.0],
                     [4.0, 5.0, 6.0]])  # shape: (2, 3)
col_vector = torch.tensor([[1000.0],
                           [2000.0]])   # shape: (2, 1)
result = data + col_vector
print(result)
# tensor([[1001., 1002., 1003.],
#         [2004., 2005., 2006.]])

tensor([[1001., 1002., 1003.],
        [2004., 2005., 2006.]])


## Instructions

1. Subtract the `user_bias` from each user's ratings (each row) and assign to bias_corrected.

1. Subtract the `item_bias` from each item's ratings (each column) and assign to item_corrected.

1. Add the `global_adjustment` to all ratings and assign to globally_adjusted.

1. Print the shape of each result to confirm broadcasting worked correctly.

In [14]:
import torch

# User ratings matrix: 3 users × 4 items
ratings = torch.tensor([[4.0, 3.5, 5.0, 2.0],
                        [3.0, 4.0, 3.5, 4.5],
                        [5.0, 2.5, 4.0, 3.0]])
user_bias = torch.tensor([[0.2],                        
                          [-0.1],                       
                          [0.3]])  
item_bias = torch.tensor([0.1, -0.2, 0.0, 0.1])
global_adjustment = 0.5  

# Use broadcasting to apply adjustments
bias_corrected = ratings - user_bias
print(bias_corrected.shape)

item_corrected = ratings - item_bias
print(item_corrected.shape)

globally_adjusted = ratings + global_adjustment
print(globally_adjusted.shape)

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])


# 6) Working with NumPy and Extracting Values

PyTorch tensors integrate tightly with NumPy, which is great news since many data science workflows start with NumPy arrays. 

Creating a tensor from a NumPy array with `torch.from_numpy` shares memory, which means changes in one reflect in the other. Converting a tensor to NumPy with the `Tensor.numpy` method also shares memory when possible.

Notice how changing `arr[0]` automatically updated `t[0]` as well. This demonstrates memory sharing in action. While this can be efficient, sometimes we need an independent copy that won't be affected by changes to the original data.

In [ ]:
import numpy as np

arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
t = torch.from_numpy(arr) 
print(t)  # tensor([1., 2., 3.])

arr[0] = 10.0 #change the numpy array and see the effect on the tensor
print(t)  # tensor([10.,  2.,  3.])

tensor([1., 2., 3.])
tensor([10.,  2.,  3.])


**Breaking Memory Sharing with `.clone()`**

When we need an independent copy of a tensor that won't be affected by changes to the original, we use the `.clone()` method. This is particularly important when working with gradients, saving intermediate results, or when you need to modify tensor values without affecting the source.

In [16]:
# Create independent copy that doesn't share memory
original = torch.tensor([1.0, 2.0, 3.0])
independent = original.clone()
original[0] = 99.0
print(original)     # tensor([99.,  2.,  3.])
print(independent)  # tensor([1., 2., 3.]) - unchanged

# Alternative: torch.tensor() also creates a copy from existing tensors
copy_via_tensor = torch.tensor(arr)  # copies data

tensor([99.,  2.,  3.])
tensor([1., 2., 3.])


**When to use .clone():**

1. **Gradient preservation**: Save gradients before they get overwritten by subsequent calculations

1. **Experimental modifications**: Test changes on a copy while keeping the original intact

1. **Multi-step processing**: Store intermediate results that won't change when you continue processing the original

1. **Breaking unwanted sharing**: Ensure your tensor operations don't unexpectedly modify shared data

**Extracting scalar values with `.item()`**

When we have a tensor containing a single value, we often need to extract that value as a Python numerical value rather than a PyTorch tensor. The `.item()` method does exactly that:

In [17]:
# Single value tensor
loss_tensor = torch.tensor(3.14159)
loss_value = loss_tensor.item() 
print(type(loss_value))  # <class 'float'>

# Also works with computed values
mean_value = torch.tensor([1.0, 2.0, 3.0]).mean().item()
print(mean_value)  # 2.0

<class 'float'>
2.0


**Impact of memory sharing:**

Memory sharing is useful when we're working with large datasets and want to avoid duplicating data. But be careful! Unexpected changes can introduce bugs. If you're getting values you don't expect, check whether your tensors and arrays are sharing memory by modifying one and seeing if the other changes.

**Dtype tip**: NumPy defaults to `float64`; PyTorch commonly uses `float32` for model inputs and parameters. When building arrays you'll turn into tensors, prefer `dtype=np.float32` to avoid conversion overhead later.

**Reminder**: To standardize values, divide the difference between values (x) and their mean (x.mean()) by the standard deviation (x.std()).


## Instructions

1. Convert `scores_np` to a tensor scores_t with float32 dtype.

1. Standardize `scores_t` to zero mean and unit variance, assigning to `standardized_scores`.

1. Calculate the mean and standard deviation of `standardized_scores` as Python floats, then extract their values using .item() and assign them to mean_value and std_value.

1. Print `mean_value` and `std_value`.

In [ ]:
import torch
import numpy as np

scores_np = np.array([72.0, 88.0, 91.0, 65.0, 77.0])

# Convert, standardize, and extract values
scores_t = torch.tensor(scores_np,dtype=torch.float32)

standardized_scores = (scores_t - scores_t.mean())/scores_t.std()

#extract mean and std values (scalar)
mean_value = standardized_scores.mean().item() #withou item(), it will be a tensor
std_value = standardized_scores.std().item()

print(mean_value, std_value)

1.4305115314527939e-07 1.0


# 7) Matrix Operations and Element-wise Operations